# top_summary.py
import pandas as pd

# Load the CSV generated by semantic_matcher_local.py
csv_path = "results/resume_semantic_local.csv"

df = pd.read_csv(csv_path)

# Sort by final_score descending and get top 3
top_n = df.sort_values(by="final_score", ascending=False).head(3)

print("\n📊 Top 3 Resumes by Final Score:\n")
print(top_n[["resume_file", "final_score", "verdict"]])

# Optional: show all resumes with Low/Medium/High verdict counts
verdict_counts = df["verdict"].value_counts()
print("\n📈 Verdict Summary:")
print(verdict_counts)
